name: msa
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - hmmer
  - billiard
  - biopython>=1.84
  - bokeh
  - click
  - filelock
  - jinja2
  - matplotlib
  - msgpack
  - numba
  - numpy
  - pandas
  - psutil
  - requests
  - ruamel.yaml<0.18
  - scikit-learn
  - scipy
  - seaborn
  - setuptools>=18.2 